// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2TWcCX5EChf6kyx1BSiOf387o8Cz5siU',
    appId: '1:847953336398:web:a7715a3a188799f7dfcb1f',
    messagingSenderId: '847953336398',
    projectId: 'bolaodasoci2026',
    authDomain: 'bolaodasoci2026.firebaseapp.com',
    storageBucket: 'bolaodasoci2026.firebasestorage.app',
    measurementId: 'G-4DCTFHYKX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdoV324rAhVsdJ4L6wjGWBfCANP3m-IP8',
    appId: '1:847953336398:android:d327d3ece2006e11dfcb1f',
    messagingSenderId: '847953336398',
    projectId: 'bolaodasoci2026',
    storageBucket: 'bolaodasoci2026.firebasestorage.app',
  );
}
